/**
 * Pure (electron-free) resolution of the tray icon asset path, so it is unit-testable.
 *
 * The branded icons live at `<appRoot>/assets/` (provenance: branding/hive/logos/hive-favicon.svg,
 * generated by `npm run generate-icons`). The compiled tray module is `dist/tray/index.js`, so the
 * assets dir is two levels up (`dist/tray` → `dist` → `<appRoot>`). This resolves correctly both in
 * development (`desktop/assets/...`) and in the packaged app, where `dist/` and `assets/` sit side by
 * side inside `app.asar` (Electron's `nativeImage.createFromPath` reads asar paths transparently).
 */

import { join } from "node:path";

/**
 * The icon filename to load for the tray, per platform: Windows uses the multi-resolution `.ico`
 * (crisp at every tray DPI); other platforms use the 32×32 PNG.
 */
export function trayIconFile(platform: NodeJS.Platform): string {
  return platform === "win32" ? "icon.ico" : "tray-icon.png";
}

/**
 * Resolve the absolute path to the tray icon asset from the compiled tray module's directory
 * (`dist/tray`) and the platform. Assets are two levels up under `assets/`.
 */
export function resolveTrayIconPath(compiledTrayDir: string, platform: NodeJS.Platform): string {
  return join(compiledTrayDir, "..", "..", "assets", trayIconFile(platform));
}
